version: "3"
networks:
  ops:

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - 9190:9090
    networks:
      - ops

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:latest
    ports:
      - 9193:9093
    networks:
      - ops
    depends_on:
      - prometheus

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    ports:
      - 3100:3000
    networks:
      - ops
    depends_on:
      - prometheus

  rest-service:
    build: ./rest-service
    container_name: rest-service
    image: rest-service:0.0.1
    ports:
      - 8180:8080
    networks:
      - ops
