GET http://localhost:8080/api/ping
Accept: application/json

###

GET http://localhost:8180/api/ping
Accept: application/json

###

GET http://localhost:8080/actuator
Accept: application/json

###

GET http://localhost:8080/actuator/prometheus
Accept: application/json

###


