GET http://localhost:8080/api/ping
Accept: application/json

###

GET http://localhost:8181/api/ping
Accept: application/json

###

GET http://localhost:8080/actuator
Accept: application/json

###

GET http://localhost:8181/actuator
Accept: application/json

###

GET http://localhost:8080/actuator/prometheus

###

GET http://localhost:8181/actuator/prometheus

###


